MapTacToe:
  Board1:
    Participants:
      AI:
        Symbol: "circle.png"
        Difficulty: 1
        Delay: 20
        StartFirst: true
      PlayerA:
        Symbol: "cross.png"
      # Either AI or PlayerB, if both are enabled, use AI
      # PlayerB:
        # Symbol: "circle.png"
    Settings:
      Width: 3
      Height: 3
      Facing: EAST
      Win: 3
      Time: 100
      Expire: 2400
      Reset: 100
    Commands:
      Win:
        AI:
        - "say &aAI has won Tic Tac Toe %id% in fighting %loser%!"
        Player:
        - "say &a%winner% has won Tic Tac Toe %id% in fighting %loser%!"
        - "eco give %winner% 10"
      # Available: %winner% %loser%
      Lose:
        AI:
        - "say &aAI has lost Tic Tac Toe %id% in fighting %winner%!"
        Player:
        - "say &a%loser% has lost Tic Tac Toe %id% in fighting %winner%!"
        - "eco take %loser% 10"
      Draw:
        # Available: %opponent%
        AI:
        - "say &aAI has draw Tic Tac Toe %id% in fighting %opponent%!"
        # Available: %p1% %p2%
        Player:
        - "say &a%p1% has draw Tic Tac Toe %id% in fighting %p2%!"
    Locations:
      Top:
        ==: org.bukkit.Location
        world: dungeon
        x: 110.0
        y: 6.0
        z: 250.0
        pitch: 0.0
        yaw: 0.0
      Bottom:
        ==: org.bukkit.Location
        world: dungeon
        x: 110.0
        y: 4.0
        z: 248.0
        pitch: 0.0
        yaw: 0.0
    Datas:
    - "   "
    - "   "
    - "   "
  Board2:
    Participants:
      AI:
        Symbol: "circle.png"
        Difficulty: 1
        Delay: 20
        StartFirst: true
      PlayerA:
        Symbol: "cross.png"
      # Either AI or PlayerB, if both are enabled, use AI
      # PlayerB:
        # Symbol: "circle.png"
    Settings:
      Width: 3
      Height: 3
      Facing: SOUTH
      Win: 3
      Time: 100
      Expire: 2400
      Reset: 100
    Commands:
      Win:
        AI:
        - "say &aAI has won Tic Tac Toe %id% in fighting %loser%!"
        Player:
        - "say &a%winner% has won Tic Tac Toe %id% in fighting %loser%!"
        - "eco give %winner% 10"
      # Available: %winner% %loser%
      Lose:
        AI:
        - "say &aAI has lost Tic Tac Toe %id% in fighting %winner%!"
        Player:
        - "say &a%loser% has lost Tic Tac Toe %id% in fighting %winner%!"
        - "eco take %loser% 10"
      Draw:
        # Available: %opponent%
        AI:
        - "say &aAI has draw Tic Tac Toe %id% in fighting %opponent%!"
        # Available: %p1% %p2%
        Player:
        - "say &a%p1% has draw Tic Tac Toe %id% in fighting %p2%!"
    Locations:
      Top:
        ==: org.bukkit.Location
        world: dungeon
        x: 109.0
        y: 8.0
        z: 238.0
        pitch: 0.0
        yaw: 0.0
      Bottom:
        ==: org.bukkit.Location
        world: dungeon
        x: 113.0
        y: 4.0
        z: 238.0
        pitch: 0.0
        yaw: 0.0
    Datas:
    - "   "
    - "   "
    - "   "