main: to.epac.factorycraft.tictactoe.TicTacToe
version: 1.0.0
name: TicTacToe
author: i998979
description: Classic Tic Tac Toe game, but with maps & buttons
softdepend: [BKCommonLib]
api-version: 1.13

commands:
  tictactoe:
    aliases: [ttt]
    description: Main command
    
permissions:
  TicTacToe.Admin:
    description: Give access to all commands